### ISSUE TITLE
Continuous Reloading Loop

### ISSUE THREAD

**Issue by Daminite** [igorlogius/dontLoadBackgroundTabs#1] opened 2021-07-28 09:23 UTC
I'm using simple tab groups and tree style tabs and if I switch tab groups it goes into a continuous reloading loop when dontloadbackgroundtabs is turned on. I think the two extensions are both triggering in a loop.

**Comment by igorlogius** [comment] 2021-07-28 09:43
I briefly installed dontLoadBackgroundTabs (dLBT) and "Simple Tab Groups" (STG) 
then created 2 groups and played around with opening tabs and switchting between groups and creating loaded and unloaded tab.

I sadly could not reproduce the issue with just these 2 addons.

@Daminite 
Can you confirm that just these dLBT and STG do not trigger the "reloading loop" ?

**Comment by Daminite** [comment] 2021-07-28 17:51
Hmm, I've actually been trying to avoid triggering it again but it happened after I turned about 40 of tabs in a different window into it's own group then closed that window. Then the reload loop happened whenever I changed groups. I also have 
https://addons.mozilla.org/en-US/firefox/addon/loadtabonselect3
And
https://addons.mozilla.org/en-US/firefox/addon/unload-tabs
that may have contributed but those are the only other extensions that effect tab loading that I have hat the moment. 
And I resumed from a session with over 200 tabs before that. Most of those tabs were from mangadex.org

**Comment by igorlogius** [comment] 2021-07-28 19:46
Mmmh, from your description i am not 100% convinced that the issue is with dLBT ... but i did add an addional (check) to the discard mechanisme to ensure that the addon doesnt touch any tabs which are hidden, which is the mechanisem .. STG uses to manage its groups. 

Regarding the other 2 addons
`loadtabonselect3` and `unload-tabs` ... at least their names sound like they could be problematic since they seem touch on the same discard mechanism as dLBT does.

If you can identify an definit issue with one or both addons, the best i can do for now is add a warning/notice so people at least know, that there could be a problem with installing both.

**Comment by Daminite** [comment] 2021-07-28 23:41
Unload-tabs is set to be manual only and loadtabonselect3 is startup only. I've got dlbt enabled and I'll see if I can trigger the error again. With any luck it was just a one-time thing.

**Comment by Daminite** [comment] 2021-07-29 06:52
Still happens with the updated version, I can reliably trigger the error just by having dlbt enabled when I change tab groups with stg and it doesn't happen under the same circumstances when it's disabled. It doesn't happen when switching to a tab group that I've switched to before with it disabled after re-enabling it, only when switching to a group with dlbt enabled that I haven't used since closing and reopening Firefox.

**Comment by igorlogius** [comment] 2021-07-29 08:33
That sounds interesting, i'll try to reproduce it.

**Comment by igorlogius** [comment] 2021-07-29 08:40
I still cant seem to trigger the bug, could you gitve me a step by step description what you are doiing?

Something like this 

1. Create STG Group 1
2. Create STG Group 2
3. Add (loaded/unloaded) Tab to Group 1
4. Switch to Tab ... of Group 2 
5. etc. 

Thanks in advance.

**Comment by Daminite** [comment] 2021-07-29 23:59
Okay so:
1: create tab group and populate it (10+ tabs)
2: create other tab groups and populate
3: close Firefox
4: open Firefox and allow the session to finish recovering with loadtabonselect3 preventing all but the last active tab loading
5: change group while dlbt is active from stg sidebar or button.
6: force close Firefox to get it to stop because the browser becomes minimally responsive and usually won't close normally one this starts

Alternately if I switch to a tab group with dlbt off initially and then turn it back on I can then change freely to any groups that had been previously loaded despite the fact that the groups tabs are still following the startup loading rule from loadtabonselect3. Most of the tabs in question are from mangadex but the error isn't exclusive to tabs from that site.

**Comment by Daminite** [comment] 2021-07-30 07:40
Turns out that neither stg or loadtabonselect3 have a settings export option but I think I'm using stg largely at default settings. I tried flipping a few toggles that seemed relevant and if discard after hide in stg is active the error will still happen even after loading the group once with dlbt off for later tab switching.
And for loadtabonselect3, from the beginning it has been largely disabled but the prevent background tabs from loading at start option because that's all that I needed it for. Every box is unchecked except for showing a discard tab and display the restore closed tab option in the context menu. I think it's basically default as well. 

So it looks like the error is triggering in relation to hidden discarded tabs.

**Comment by igorlogius** [comment] 2021-07-30 08:44
> So it looks like the error is triggering in relation to hidden discarded tabs.

Version  0.1.2 explicitly  ignores `hidden` tabs  (src. https://github.com/igorlogius/dontLoadBackgroundTabs/blob/f0a5d214d0220de19b60524e23d1ec19638e9769/background.js#L8) 

Could you double check that you are using the latest version.

**Comment by Daminite** [comment] 2021-07-30 21:14
I am using the current version

**Comment by igorlogius** [comment] 2021-08-02 20:52
Sorry for the late reply, i am a bit occupied with work at the moment. 


So the issue with the continuous loading loop does not happen anymore with  FF 90? 
Mmh, good to know, but i cant make any connection why, oh well, thats life. 

The thing with the links on the addon page seems strange.
When i middle/ctrl click (to open in the background) the links  on the addon preference  behave the same way as  "normal" page links. Not sure what could be causing this for you. 

My general goto cuplits would be  maybe 
1. some other addon
2. some about:config preference  

If it is none of those 2 ... maybe its just a fluke ? 
Does it happen consistently?

**Comment by igorlogius** [comment] 2021-08-10 10:46
Closing this issue for now, since it "seems" to be resolved (if i did not missunderstand)

@Daminite 
If the issue with the 
"Blank tab with links on addon preference page " persist, i would request that you open a seperate issue for it, just to keep things organized.

**Closed by igorlogius** 2021-08-10 10:46 UTC
Labels: in review
